### ISSUE TITLE
Style File Menu

### ISSUE THREAD

**Issue by lodge93** [Roastero/Openroast#23]
The file menu and bar needs styled on Windows and Ubuntu

**Comment by SenorFusion** [comment]
Mark,

Could you elaborate on this? 

Which file menu? System application menu? (File | Edit | View | etc ) ?

On Ubuntu, unless I am missing something there is currently no system application menu at all. (Though I'm running Cinnamon, I'll check on Unity)

**Comment by lodge93** [comment]
Yes, the File, Edit, View menu is plain on Windows and Ubuntu, here a screenshot under unity

![screen shot 2015-04-28 at 9 25 35 pm](https://cloud.githubusercontent.com/assets/3886576/7383438/4b7b31be-eded-11e4-9ca8-490828c28ff5.png)

**Comment by int3ll3ct** [comment]
Those are OS-level items that are out of the application's control.  Closing.
