### ISSUE TITLE
Allow for cooling in the middle of a recipe

### ISSUE THREAD

**Issue by CCoffie** [Roastero/Openroast#25]

**Comment by lodge93** [comment]
Fixed with 393539edf3658b9a0d049dff39cc9cfe38598811

**Comment by lodge93** [comment]
Cooling phase can be in the middle, it just cannot be at the beginning.

**Comment by lodge93** [comment]
At this point, Openroast will only support cooling at the end of a roast as is the most normal usage of the cooling functionality. If there is a need further down the road, I will reopen this issue.
