### ISSUE TITLE
"Steps" Titles Cut Off in Recipe Window

### ISSUE THREAD

**Issue by SenorFusion** [Roastero/Openroast#26]
On my system, the default window size (800 x 600) of the New Recipe or Edit Recipe window cuts off the titles of the headers in the "Steps" section.

![ubuntu-headers-cut-off](https://cloud.githubusercontent.com/assets/1929777/7382430/597a9d36-edd4-11e4-8a18-5e0e9b19409d.png)

Could: 
-smaller text size
-change default window size
-make the "Description" and "Steps" columns 40/60 instead of 50/50

**Comment by int3ll3ct** [comment]
I don't believe this is an issue at this point - closing.
