### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by jclif** [Roastero/Openroast#31]
I noticed that the setup steps include a section about patching PySerial, but that the folder 'PySerial Patched Files' is no longer tracked in master.

**Comment by lodge93** [comment]
I apologize, I have just refactored a large portion of code this week and have not had a chance to update the documentation yet. In the meantime, install the master branch of pyserial directly at https://github.com/pyserial/pyserial as they have it patched. Also if you are using El Capitan, there are currently no fully functioning drivers available for CH341.

**Comment by jclif** [comment]
That definitely understandable. I didn't have any issues running with the  latest version of pyserial.

I am still having some issue getting this to work on OSX, though. Even though I'm still hanging out on Yosemite, I can't seem to get past the roaster detection step (having tried a few different drivers and the sudo nvram boot-args="kext-dev-mode=1" and restart instruction). Do you know of any gotchas that might be hanging around?

**Comment by lodge93** [comment]
Make sure you are running (Pyserial version 3.0)[https://github.com/pyserial/pyserial/releases/tag/v3.0b1] or latter. The current version in pypi is version 2.7.

Also, I have just released packages for (Openroast Version 1.0.0)[https://github.com/Roastero/Openroast/releases/tag/v1.0.0] if you want to give the packed version a try.

**Comment by jclif** [comment]
I got it working via cli but the graphing capabilities didn't seem to be working. The packaged version seems to be working just fine, though. The only thing that I notice is that the roaster temps will occasionally shoot up and stop the roast:

<img width="1173" alt="screen shot 2015-11-16 at 9 34 09 pm" src="https://cloud.githubusercontent.com/assets/3463691/11201201/fd0d4c0e-8ca9-11e5-8c70-72306978007b.png">

Since this a new roaster, I would like to believe that the temperature sensors aren't faulty, but that might be the case.

Have you encountered these issues before?

**Comment by jclif** [comment]
I also notice that the target temp on the top right doesn't seem to update according to the recipe.

It seems to be following the recipe all right though. Just really consistently bails out due to high temp I think (is there an upper limit?).

**Comment by lodge93** [comment]
Ah yes, try pulling on your local freshroastsr700 repo and reinstall the module. That issue was a few commits ago. The problem is the arduinos in the Freshroastsr700 are really cheap, and often reset themselves or send bad data. I have had a lot of issues trying to write the module in way that is robust enough to handle any and all hardware malfunctions.

**Comment by jclif** [comment]
In the end, I made it though to the end just by hitting the roast button a few times until it started back up again, haha:

<img width="1917" alt="screen shot 2015-11-16 at 9 52 41 pm" src="https://cloud.githubusercontent.com/assets/3463691/11201457/70840fd6-8cac-11e5-82a3-b46114e6a7c5.png">

It ended up being a little dark due to the debugging in the beginning, but the beans smell amazing! Thanks for the help! I'll try reinstalling the freshroastr repo later and see if that does it.

**Comment by lodge93** [comment]
Hold on, I was able to reproduce the issue myself. I will look into this and work on a fix.

**Comment by jclif** [comment]
Appreciate the work, dude. I haven't flexed my python muscles in a while, but I'd love to take a look and maybe contribute in the near future.

**Comment by jclif** [comment]
The jumps in temp appear to be occurring with some regularity around where the the settings change, i.e. for the Diedrich style, at the end of the 30 second period, then every 1 min afterward.

**Comment by lodge93** [comment]
I just applied a fix to this issue https://github.com/Roastero/freshroastsr700/issues/7, let me know if the update works!

**Comment by kmorey** [comment]
In the vein of documentation updates:

Can you update requirements.txt with library versions or post a pip freeze of your environment? My windows installer has some issues (icon doesn't show properly and once you install and run, it displays a shell window in addition to the main window) as well as the actual Openroast UI doesn't update as it's running. Want to eliminate me having the wrong versions of libraries before I dig in much farther.

Also `python setup.py build_msi` doesn't work for me but `python setup.py bdist --format=msi` does.

**Comment by lodge93** [comment]
Ah yes, I have to update the setup.py to work on both platforms. I will work on that next in addition to adding the software versions I have found to work.

**Comment by lodge93** [comment]
Alright, I have added a version to matplotlib, updated the setup.py to package correctly, and updated all documentation. I have added [packaging instructions](https://github.com/Roastero/Openroast/wiki/Packaging-Openroast) as well. Let me know if anything does not seem to be correct.
