### ISSUE TITLE
Tweaking during roast are not saved in recipe

### ISSUE THREAD

**Issue by gedit58** [Roastero/Openroast#45]
Using Openroast 1.0.1 for Win64:
It would be nice to have modifications of fan/temp/time, saves as a new step into the roast profile.
Base profile is created, with Target temp for each step. But during roast, I needed to change the fan speed and temp up steps. But those were not saved to the roast profile and then I cannot repeat the same roast.

**Comment by int3ll3ct** [comment]
Given how Openroast is written, it would be difficult to accommodate this request without a significant rethink of the UI.

**Comment by int3ll3ct** [comment]
While this is a noble idea, it breaks most of the app's architecture and would require an extensive rewrite. As a result, this will not be attempted at this time.
