### ISSUE TITLE
found roaster. connecting forever

### ISSUE THREAD

**Issue by eggxpert** [Roastero/Openroast#63]
Macbook air, USB driver and OpenRoast installed, cannot find SR700 on OpenRoast 1.2.0rc3; found roaster on OpenRoast 1.2.1, but connecting forever. I dunno how to troubleshoot, please help. Thanks!

**Comment by int3ll3ct** [comment]
I've been away from this for a while, what version of Mac OS are you running, on which MacBook Air generation? It is more likely to be driver related than app related. If there is more than one USB connector on your laptop, try them all. There is a general issue with certain USB 3 ports and the SR 700, for example on my Dell XPS 9343 laptop it only works in the left USB port and not the right one... Also some people have had success with using USB 2.0 hubs into their computer, and plugging the SR 700 into that.

**Comment by eggxpert** [comment]
Thanks @int3ll3ct , i got it working by restart/plug and unplug both sr700 and computer a few times. i dunno what's the root cause, but i encounter this scenario a few times, just resolved by switching sr700 on/off can resolve. wondering where is the OR log/debug file, so next time i can have a look and provide more information.

**Comment by int3ll3ct** [comment]
OK I'll close this now.  I'm adding a reliable logging mechanism as a feature for the next version.

**Comment by jzila** [comment]
I'm seeing this too, except I don't have a workaround. All my USB ports are USB-C, and I'm using the dongle that came with my laptop. I'm running Ubuntu 18.04. I can help debug if there are instructions for injecting my own freshroastsr700 package.
